
all: py-deps apt-deps colcon-deps

py-deps:
	pip3 install --user \
		catkin-pkg \
		colcon-common-extensions \
		flake8-blind-except \
		flake8-builtins \
		flake8-class-newline \
		flake8-comprehensions \
		flake8-deprecated \
		flake8-import-order \
		flake8-quotes \
		rosdep \
		rosdistro \
		rospkg \
		vcstool \
		pytest-repeat

apt-deps:
	sudo apt install -y \
		build-essential \
		cmake \
		flake8 \
		git \
		python3-flake8 \
		python3-flake8-docstrings \
		python3-flake8-polyfill \
		python3-pip \
		python3-pytest \
		python3-pytest-cov \
		python3-pytest-flake8 \
		python3-pytest-rerunfailures \
		python3-setuptools \
		wget

colcon-deps:
	sudo apt install -y \
		bison \
		curl \
		libacl1-dev \
		libasio-dev \
		libbullet-dev \
		libeigen3-dev \
		libfreetype-dev \
		liblog4cxx-dev \
		libopencv-dev \
		libtinyxml2-dev \
		libxaw7-dev \
		libxrandr-dev \
		pyqt5-dev \
		pyqt5-dev-tools \
		python3-lark \
		python3-opencv \
		python3-sip-dev \
		qtbase5-dev \
		qtbase5-dev-tools \
		qttools5-dev \
		qttools5-dev-tools \
		sip-dev
